export interface SpecEntry {
  id: string;
  title: string;
  link?: string;
}

export interface SpecSection {
  folder: string;
  title: string;
  description: string;
  iconName: "file-text" | "alert-triangle" | "compass" | "terminal" | "shield-check" | "palette";
  color: string;
  entries: SpecEntry[];
}

export const sections: SpecSection[] = [
  {
    folder: "01-app",
    title: "Application Specifications",
    description: "Feature specs, command designs, and refactor documentation for the gitmap CLI.",
    iconName: "file-text",
    color: "text-primary",
    entries: [
      { id: "01", title: "Overview" },
      { id: "02", title: "CLI Interface" },
      { id: "03", title: "Scanner" },
      { id: "04", title: "Formatter" },
      { id: "05", title: "Cloner" },
      { id: "06", title: "Config", link: "/config" },
      { id: "07", title: "Data Model" },
      { id: "08", title: "Acceptance Criteria" },
      { id: "09", title: "Build & Deploy" },
      { id: "10", title: "GitHub Desktop" },
      { id: "11", title: "Desktop Sync" },
      { id: "12", title: "Release Command", link: "/release" },
      { id: "13", title: "Release Data Model" },
      { id: "14", title: "Latest Branch" },
      { id: "15", title: "Date Display Format" },
      { id: "16", title: "Database" },
      { id: "17", title: "Repo Grouping" },
      { id: "18", title: "Compliance Audit" },
      { id: "19", title: "List Versions" },
      { id: "20", title: "Revert" },
      { id: "21", title: "List Releases" },
      { id: "22", title: "Scan Release Import" },
      { id: "23", title: "SEO Write" },
      { id: "24", title: "Amend Author" },
      { id: "25", title: "Command History", link: "/history" },
      { id: "26", title: "Stats", link: "/stats" },
      { id: "27", title: "Bookmarks", link: "/bookmarks" },
      { id: "28", title: "Export", link: "/export" },
      { id: "29", title: "Import", link: "/import" },
      { id: "30", title: "Profiles", link: "/profile" },
      { id: "31", title: "cd" },
      { id: "32", title: "Watch", link: "/watch" },
      { id: "33", title: "Diff Profiles", link: "/diff-profiles" },
      { id: "34", title: "Clone Progress" },
      { id: "35", title: "Docs Site" },
      { id: "36", title: "GoMod Rename", link: "/gomod" },
      { id: "37", title: "Project Detection", link: "/project-detection" },
      { id: "38", title: "Command Help" },
      { id: "39", title: "Shell Completion" },
      { id: "40", title: "Enhanced Groups & Listing" },
      { id: "41", title: "Go Release Assets" },
      { id: "42", title: "Cross-Platform" },
      { id: "43", title: "Interactive TUI", link: "/interactive" },
      { id: "44", title: "List DB Diagnostic" },
      { id: "45", title: "Release Pending Metadata" },
      { id: "46", title: "Clear Release JSON", link: "/clear-release-json" },
      { id: "47", title: "Zip Groups", link: "/zip-group" },
      { id: "48", title: "Repo Aliases", link: "/alias" },
      { id: "49", title: "Changelog Generate", link: "/changelog-generate" },
      { id: "50", title: "SSH Keys", link: "/ssh" },
      { id: "51", title: "Prune", link: "/prune" },
      { id: "52", title: "Upload Retry" },
      { id: "53", title: "Offline Detection" },
      { id: "54", title: "Process Locking" },
      { id: "55", title: "Temp Release", link: "/temp-release" },
      { id: "56", title: "Unified .gitmap Dir" },
      { id: "57", title: "Skip-Meta Integration Test" },
      { id: "58–78", title: "Refactors (workflow, dispatch, archive, autocommit, SEO, branches, assets, TUI, aliases, ops, status, exec, logs, compress)" },
      { id: "axios-version-control", title: "Axios Version Control" },
      { id: "59", title: "Clone Next", link: "/clone-next" },
      { id: "81", title: "Developer Tool Installer" },
      { id: "82", title: "One-Liner Install Scripts" },
      { id: "83", title: "Install Bootstrap One-Liner" },
      { id: "60", title: "Help Dashboard", link: "/help-dashboard" },
      { id: "65", title: "Update Path Recovery" },
    ],
  },
  {
    folder: "02-app-issues",
    title: "Issue Post-Mortems",
    description: "Root-cause analyses and resolution records for production bugs.",
    iconName: "alert-triangle",
    color: "text-yellow-500",
    entries: [
      { id: "01", title: "Update File Lock" },
      { id: "02", title: "Update Flow Spec Alignment" },
      { id: "03", title: "Update Sync Lock Loop" },
      { id: "04", title: "Database Path Resolution" },
      { id: "05", title: "List Empty DB Path" },
      { id: "06", title: "Release Orphaned Metadata" },
      { id: "07", title: "Zip Group Release Silent Failure" },
      { id: "08", title: "Autocommit Push Rejection" },
      { id: "09", title: "List Releases Repo Source" },
      { id: "10", title: "Legacy UUID Detection" },
      { id: "11", title: "Auto Legacy Dir Migration" },
      { id: "12", title: "Legacy ID Migration" },
      { id: "13", title: "Release Pipeline Directory Error" },
      { id: "14", title: "Security Hardening (GoSec Fixes)" },
      { id: "15", title: "Installer Crashes — Progress Bar & Binary Detection" },
      { id: "16", title: "CI Passthrough Gate Pattern" },
    ],
  },
  {
    folder: "03-general",
    title: "Design Guidelines",
    description: "Reusable architectural patterns and coding standards — generic and shareable across projects.",
    iconName: "compass",
    color: "text-green-500",
    entries: [
      { id: "01", title: "CLI Design Patterns" },
      { id: "02", title: "PowerShell Build & Deploy" },
      { id: "03", title: "Self-Update Mechanism" },
      { id: "04", title: "Output Formatting" },
      { id: "05", title: "Configuration Pattern" },
      { id: "06", title: "Code Style Rules" },
      { id: "07", title: "Date Display Format" },
      { id: "08", title: "CI Pipeline Architecture" },
    ],
  },
  {
    folder: "03-tasks",
    title: "Task Specifications",
    description: "Detailed task specs for feature implementation, standardization, and process improvements.",
    iconName: "file-text",
    color: "text-cyan-500",
    entries: [
      { id: "01", title: "NPP Installation & Settings Shortcut Standardization" },
    ],
  },
  {
    folder: "04-generic-cli",
    title: "Generic CLI Blueprint",
    description: "A production-quality CLI implementation blueprint usable as a starting point for any Go CLI project.",
    iconName: "terminal",
    color: "text-blue-400",
    entries: [
      { id: "01", title: "Overview", link: "/generic-cli" },
      { id: "02", title: "Project Structure" },
      { id: "03", title: "Subcommand Architecture" },
      { id: "04", title: "Flag Parsing" },
      { id: "05", title: "Configuration" },
      { id: "06", title: "Output Formatting" },
      { id: "07", title: "Error Handling" },
      { id: "08", title: "Code Style" },
      { id: "09", title: "Help System" },
      { id: "10", title: "Database" },
      { id: "11", title: "Build & Deploy" },
      { id: "12", title: "Testing" },
      { id: "13", title: "Checklist" },
      { id: "14", title: "Date Formatting" },
      { id: "15", title: "Constants Reference" },
      { id: "16", title: "Verbose Logging" },
      { id: "17", title: "Progress Tracking" },
      { id: "18", title: "Batch Execution" },
      { id: "19", title: "Shell Completion" },
    ],
  },
  {
    folder: "05-coding-guidelines",
    title: "Coding Guidelines",
    description: "Universal code quality rules — naming, structure, and maintainability standards for all languages.",
    iconName: "shield-check",
    color: "text-orange-500",
    entries: [
      { id: "01", title: "Code Quality Improvement" },
      { id: "02", title: "Go Code Style" },
      { id: "03", title: "Naming Conventions" },
      { id: "04", title: "Error Handling Patterns" },
      { id: "05", title: "File & Project Structure" },
      { id: "06", title: "Testing Patterns" },
      { id: "07", title: "Logging & Observability" },
      { id: "08", title: "Security & Secrets" },
      { id: "09", title: "Performance & Optimization" },
      { id: "10", title: "API Design" },
      { id: "11", title: "Database Patterns" },
      { id: "12", title: "Documentation Standards" },
      { id: "13", title: "Dependency Management" },
      { id: "14", title: "Git Workflow" },
      { id: "15", title: "Monitoring & Alerting" },
      { id: "16", title: "Concurrency Patterns" },
      { id: "17", title: "CI/CD Patterns" },
      { id: "18", title: "Resilience Patterns" },
      { id: "19", title: "Internationalization" },
      { id: "20", title: "Accessibility" },
      { id: "21", title: "Configuration Management" },
      { id: "22", title: "Observability Dashboards" },
      { id: "23", title: "Monitoring & Alerting (Detailed)" },
      { id: "24", title: "Data Migration" },
      { id: "25", title: "Code Review" },
      { id: "26", title: "Feature Flags" },
      { id: "27", title: "Dependency Management" },
      { id: "28", title: "Git Workflow" },
      { id: "29", title: "CI SHA-Based Build Deduplication" },
    ],
  },
  {
    folder: "06-design-system",
    title: "Design System",
    description: "Complete visual design reference — colors, typography, code blocks, component patterns, and syntax themes.",
    iconName: "palette",
    color: "text-primary",
    entries: [
      { id: "01", title: "Colors & Themes (Root)" },
      { id: "02", title: "Typography" },
      { id: "03", title: "Code Blocks" },
      { id: "04", title: "Component Patterns" },
      { id: "05", title: "Syntax Token Colors" },
    ],
  },
];
