<#
.SYNOPSIS
    Clone all repositories from a gitmap scan.
.DESCRIPTION
    Auto-generated by gitmap. Run this script to clone all
    discovered repositories, preserving the original folder structure.
#>

param(
    [string]$TargetDir = "."
)

$ErrorActionPreference = "Stop"
Set-Location $TargetDir


Write-Host ""
Write-Host "  ╔══════════════════════════════════════╗" -ForegroundColor DarkCyan
Write-Host "  ║          gitmap clone script         ║" -ForegroundColor DarkCyan
Write-Host "  ╚══════════════════════════════════════╝" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Cloning 1 repositories..." -ForegroundColor Cyan
Write-Host ""

$succeeded = 0
$failed = 0

Write-Host "  [1/1] " -ForegroundColor Magenta -NoNewline
Write-Host "gitmap-v3" -ForegroundColor White
$parentDir = Split-Path "." -Parent
if ($parentDir -and -not (Test-Path $parentDir)) {
    New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
}
$cloneResult = git clone -b main https://github.com/alimtvnetwork/gitmap-v3.git "." 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "  ✓ Cloned successfully" -ForegroundColor Green
    $succeeded++
} else {
    Write-Host "  ✗ Clone failed: $cloneResult" -ForegroundColor Red
    $failed++
}

Write-Host ""
Write-Host "  ══════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host "  ✓ Succeeded: $succeeded" -ForegroundColor Green
Write-Host "  ✗ Failed:    $failed" -ForegroundColor Red
Write-Host "  ══════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Done!" -ForegroundColor Green
Write-Host ""
