<#
.SYNOPSIS
    Register cloned repositories with GitHub Desktop.
.DESCRIPTION
    Auto-generated by gitmap. Run this script after cloning
    to add all repositories to GitHub Desktop.
    Requires GitHub Desktop CLI (github) to be available in PATH.
#>

param(
    [string]$BaseDir = "."
)

# Check if GitHub Desktop CLI is available
$ghDesktop = Get-Command "github" -ErrorAction SilentlyContinue
if (-not $ghDesktop) {
    Write-Host ""
    Write-Host "  ✗ GitHub Desktop CLI not found." -ForegroundColor Red
    Write-Host "    Install GitHub Desktop and ensure 'github' is in your PATH." -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

Write-Host ""
Write-Host "  ╔══════════════════════════════════════╗" -ForegroundColor DarkCyan
Write-Host "  ║     gitmap — GitHub Desktop         ║" -ForegroundColor DarkCyan
Write-Host "  ╚══════════════════════════════════════╝" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Registering 1 repositories..." -ForegroundColor Cyan
Write-Host ""

$succeeded = 0
$failed = 0

Write-Host "  [1/1] " -ForegroundColor Magenta -NoNewline
Write-Host "gitmap-v3" -ForegroundColor White
$repoPath = Join-Path $BaseDir "."
$repoPath = (Resolve-Path $repoPath -ErrorAction SilentlyContinue).Path
if ($repoPath -and (Test-Path $repoPath)) {
    try {
        github $repoPath 2>&1 | Out-Null
        Write-Host "  ✓ Added to GitHub Desktop" -ForegroundColor Green
        $succeeded++
    } catch {
        Write-Host "  ✗ Failed: $_" -ForegroundColor Red
        $failed++
    }
} else {
    Write-Host "  ✗ Path not found: ." -ForegroundColor Red
    $failed++
}

Write-Host ""
Write-Host "  ══════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host "  ✓ Registered: $succeeded" -ForegroundColor Green
Write-Host "  ✗ Failed:     $failed" -ForegroundColor Red
Write-Host "  ══════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "  Done!" -ForegroundColor Green
Write-Host ""
